#ifndef TASK_UI_H
#define TASK_UI_H

/**
 * @file Task_UI.h
 * @brief UART command-line interface task.
 * @details
 *   TaskUI receives characters from USART2 using interrupt-driven HAL UART
 *   reception, echoes user input, builds command strings, and exposes parsed
 *   commands to the top-level cooker task. The parser recognizes short human
 *   commands used during development and bench testing.
 */

#include "Task.h"
#include "main.h"
#include <cstddef>
#include <cstdint>

/** @brief USART2 handle generated by STM32CubeMX and defined in main.cpp. */
extern UART_HandleTypeDef huart2;

/**
 * @brief Print a null-terminated string to the debug/user terminal.
 * @param str Null-terminated character string to transmit.
 */
extern void print_str(const char* str);

/** @brief Shared formatted-print buffer allocated in main.cpp. */
extern char print_buf[100];

/**
 * @class TaskUI
 * @brief Non-blocking UART command parser and echo interface.
 * @details
 *   The UI task is responsible only for collecting and parsing user input.
 *   It does not execute commands directly; instead it stores a pending command
 *   that TaskCooker consumes on its next run() pass. This keeps the interrupt
 *   callback short and the command effects centralized in the cooker task.
 */
class TaskUI : public Task {
public:
  /**
   * @enum State
   * @brief Detailed UI task state.
   */
  enum class State {
    Uninitialized, /**< UART receive has not yet been armed. */
    Idle, /**< Waiting for user input. */
    CommandReady, /**< A complete parsed command is waiting to be consumed. */
    Fault /**< UART receive could not be armed or another UI fault occurred. */
  };

  /**
   * @enum Command
   * @brief Parsed user commands understood by the cooker firmware.
   */
  enum class Command {
    None, /**< No command is pending or the command was empty. */
    Home, /**< Home the system before cooking. */
    Start, /**< Start a cook cycle. */
    Stop, /**< Request a normal stop and removal move. */
    EmergencyStop, /**< Immediately fault and stop all motion. */
    Reset, /**< Clear Done/Fault state for another cook cycle. */
    Status /**< Print a one-line status report. */
  };

  /** @brief Construct the UI task. */
  TaskUI();

  /**
   * @brief Execute one non-blocking UI update.
   * @details
   *   Prints the startup prompt on first run and makes sure USART2 interrupt
   *   reception remains armed. Input is primarily handled from the HAL UART
   *   receive-complete callback.
   */
  void run() override;

  /**
   * @brief Get generic task health status.
   * @return Uninitialized before startup, Fault on UART fault, otherwise Running.
   */
  Status getStatus() const override;

  /**
   * @brief Get the detailed UI task state.
   * @return Current TaskUI::State value.
   */
  State getState() const;

  /**
   * @brief Consume and clear the pending command.
   * @return Most recent parsed command, or Command::None if none is pending.
   */
  Command consumeCommand();

  /**
   * @brief HAL UART receive-complete callback entry point for the UI task.
   * @param huart UART handle that completed a receive operation.
   * @details
   *   The global HAL_UART_RxCpltCallback forwards to this method. Characters
   *   received on USART2 are appended to the command line and echo handling is
   *   performed before reception is re-armed.
   */
  void onUartReceiveComplete(UART_HandleTypeDef* huart);

private:
  /** @brief Maximum number of characters stored for one command line. */
  static constexpr size_t kCommandBufferSize = 32;

  /** @brief Current detailed state of the UI task. */
  State state_ = State::Uninitialized;

  /** @brief Command waiting for TaskCooker to consume. */
  Command pending_command_ = Command::None;

  /** @brief Null-terminated command line buffer. */
  char command_buffer_[kCommandBufferSize] = {};

  /** @brief Current number of characters stored in command_buffer_. */
  size_t command_length_ = 0;

  /** @brief Single-byte USART2 receive buffer used by HAL_UART_Receive_IT(). */
  uint8_t rx_byte_ = 0;

  /** @brief True when an interrupt receive operation is currently active. */
  bool rx_armed_ = false;

  /** @brief True if the current command line exceeded kCommandBufferSize. */
  bool overflowed_ = false;

  /** @brief Arm USART2 to receive the next character by interrupt. */
  void armReceive();

  /**
   * @brief Process one received character.
   * @param c Character received from the UART terminal.
   */
  void handleReceivedChar(char c);

  /** @brief Parse and store a completed command line. */
  void handleCompletedLine();

  /** @brief Clear the command buffer and overflow flag. */
  void clearCommandBuffer();

  /**
   * @brief Echo one printable character back to the terminal.
   * @param c Character to echo.
   */
  void echoChar(char c);

  /**
   * @brief Echo a null-terminated string to the terminal.
   * @param str String to transmit.
   */
  void echoString(const char* str);

  /**
   * @brief Parse a command string into a Command value.
   * @param command Null-terminated command line.
   * @return Parsed command, or Command::None for unknown/empty input.
   */
  Command parseCommand(const char* command) const;

  /**
   * @brief Convert an ASCII letter to lowercase.
   * @param c Character to convert.
   * @return Lowercase version of c if it was A-Z, otherwise c unchanged.
   */
  static char toLower(char c);

  /**
   * @brief Compare two null-terminated strings for exact equality.
   * @param a First string.
   * @param b Second string.
   * @return true when both strings contain identical characters.
   */
  static bool stringsEqual(const char* a, const char* b);
};

#endif /* TASK_UI_H */
